CommunityToolkit/Windows

- .github/workflows/build.yml
Fixes #3
Pretty sure we just commented this out, now that the repo is public this should just work again. I added the repo back in the [TestSpace portal](https://communitytoolkit.testspace.com/).
Note: We'll need to add the checks in the branch protections once these are running:
The testspaces one (should appear searchable pretty easily once it has run once in the job _successfully_):
> Re-enable Testspaces Test Reporting

- components/Primitives/src/CommunityToolkit.WinUI.Controls.Primitives.csproj
- components/RangeSelector/src/CommunityToolkit.WinUI.Controls.RangeSelector.csproj
- components/Sizers/src/CommunityToolkit.WinUI.Controls.Sizers.csproj
- components/Triggers/src/CommunityToolkit.WinUI.Controls.Triggers.csproj
Progress towards #43. Several components mistakenly used the default PackageId, which simply uses the name of the component and did not include the `Controls` moniker:
The already published packages being replaced will need to be marked as deprecated.
> Fixed PackageId for control-based components

- components/Triggers/src/CommunityToolkit.WinUI.Triggers.csproj
`Triggers` was still referencing `CommunityToolkit.WinUI.Controls.Triggers` in the .csproj file. This PR removes the `Controls` part.
> [Chore] Removing controls in .csproj

- components/Sizers/src/CommunityToolkit.WinUI.Controls.Sizers.csproj
- components/Sizers/src/ContentSizer/ContentSizer.Properties.cs
- components/Sizers/tests/ContentSizerTestInitialLayout.xaml
- components/Sizers/tests/ContentSizerTestInitialLayout.xaml.cs
- components/Sizers/tests/ExampleSizerBaseTestClass.cs
- components/Sizers/tests/Sizers.Tests.projitems
Fixes #85
ContentSizer was overwriting Width to Zero causing initial layout problems of a component, instead this code is removed as it is not needed to maintain the same behavior. Added a test to validate the old behavior was incorrect and the new desired behavior should work.
See more in linked issue of the details of this.
Basically, this PR:
- adds a unit test to validate the desired correct behavior (failing before, passing now).
- removes code which is unneeded for the proper functioning of the component anyway.
- bumps version number
> Fixes #85 - ContentSizer manipulating component Width to Zero on load

- components/Sizers/src/CommunityToolkit.WinUI.Controls.Sizers.csproj
- components/Sizers/src/SizerBase.xaml
@michael-hawker pointed out that with the visual refresh we lost the ability to set the `Padding` and `CornerRadius`.
This PR introduces the following changes:
- Renaming `SizerBaseMargin` to `SizerBasePadding`
- The `Padding` and `CornerRadius` can now be set for better customization:
> Improved styling customization SizerBase

- components/CameraPreview/src/CommunityToolkit.WinUI.Controls.CameraPreview.csproj
This pr corrects the PackageId for the `CameraPreview` component. This component is in the `CommunityToolkit.WinUI.Controls` namespace, but the package ID was not set to reflect that.
> Fix package id for CameraPreview

- components/Extensions/samples/FrameworkElementAncestorSample.xaml
- components/Extensions/samples/FrameworkElementAncestorSample.xaml.cs
- components/Extensions/samples/FrameworkElementExtensions.md
- components/Extensions/src/Element/FrameworkElementExtensions.Mouse.cs
- components/Extensions/src/Element/FrameworkElementExtensions.RelativeAncestor.cs
- components/Extensions/tests/BitmapIconExtensionTestPage.xaml
- components/Extensions/tests/BitmapIconExtensionTests.cs
- components/Extensions/tests/Element/FrameworkElementExtensionsTests.RelativeAncestor.cs
- components/Extensions/tests/Element/FrameworkElementRelativeAncestorDataTemplateTestPage.xaml
- components/Extensions/tests/Element/FrameworkElementRelativeAncestorDataTemplateTestPage.xaml.cs
- components/Extensions/tests/Extensions.Tests.projitems
Adds a new sample for this extension, works on UWP and WASDK. Didn't test WASM yet.
Maybe should try adding a test too...
Not sure if any other info should be provided here, thoughts @Arlodotexe? These could be good things to start shoring up or finishing the docs/sample migration of.
Also fixes #106
Adds tests for #107 
Supersedes https://github.com/CommunityToolkit/WindowsCommunityToolkit/pull/4322
> Add sample/tests for FrameworkElementExtensions.Ancestor/Type

- .vscode/settings.json
- components/SettingsControls/src/CommunityToolkit.WinUI.Controls.SettingsControls.csproj
This PR is a hotfix for SettingsControl. The most recent version `8.0.0-beta.1` seems to only have uwp, wasdk and wasm enabled. 
Building a nuget package locally, the missing TFMs were available. Bumping the version will allow us to push a new package, enabling the missing TFMs.
> Bumped SettingsControl version number, enable other TFMs

- .github/workflows/build.yml
- .vscode/launch.json
- Directory.Build.props
Separating out from #138 
Follow-on from https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/99
138 isn't building in linux for some reason related to converters, but everything works fine locally. Figured would try splitting this out first to see if that changes anything.
> Add Converters property to directory props to build converters from source for sample app

- components/Converters/samples/BoolNegationConverterSample.xaml
- components/Converters/samples/BoolNegationConverterSample.xaml.cs
- components/Converters/samples/BoolToObjectConverterSample.xaml
- components/Converters/samples/BoolToObjectConverterSample.xaml.cs
- components/Converters/samples/BoolToVisibilityConverterSample.xaml
- components/Converters/samples/BoolToVisibilityConverterSample.xaml.cs
- components/Converters/samples/CollectionVisibilityConverterSample.xaml
- components/Converters/samples/CollectionVisibilityConverterSample.xaml.cs
- components/Converters/samples/ColorToDisplayNameConverterSample.xaml
- components/Converters/samples/ColorToDisplayNameConverterSample.xaml.cs
- components/Converters/samples/Converters.Samples.csproj
- components/Converters/samples/Converters.md
- components/Converters/samples/DoubleToObjectConverterSample.xaml
- components/Converters/samples/DoubleToObjectConverterSample.xaml.cs
- components/Converters/samples/DoubleToVisibilityConverterSample.xaml
- components/Converters/samples/DoubleToVisibilityConverterSample.xaml.cs
- components/Converters/samples/EmptyStringToObjectConverterSample.xaml
- components/Converters/samples/EmptyStringToObjectConverterSample.xaml.cs
- components/Converters/samples/FileSizeToFriendlyStringConverterSample.xaml
- components/Converters/samples/FileSizeToFriendlyStringConverterSample.xaml.cs
- components/Converters/samples/StringFormatConverterSample.xaml.cs
- components/Converters/samples/StringVisibilityConverterSample.xaml
- components/Converters/samples/StringVisibilityConverterSample.xaml.cs
- components/Converters/samples/TypeToObjectConverterSample.xaml
- components/Converters/samples/TypeToObjectConverterSample.xaml.cs
- components/Converters/samples/VisibilityToBoolConverterSample.xaml
- components/Converters/samples/VisibilityToBoolConverterSample.xaml.cs
- components/Converters/src/ColorToDisplayNameConverter.cs
- Adding a few new samples for various converters. (No sample for e.g. TaskResultConverter and ResourceStringConverter as these might not be used that much?) Maybe a code 1 liner is enough?
Known issues:
- The EmptyCollection converter sample does not seem to work.. Converter doesn't get triggered when the collection changes?
- ColorToDisplayName sample not working for WASDK
@michael-hawker Would love to get your feedback on these samples - wanted to keep them as simple as possible to let devs quickly copy-and-paste what they need vs. complex use cases - especially since Converters are pretty straightforward to work with?
> [Converters] Adding updated samples

- Directory.Build.props
Helps with UWP project heads and old-project system now for some reason after single-experiment heads broke with #152 #164
There's still an issue with some projects (like Behaviors) that reference other projects within their source projects (like Animations).
The UWP single-component head isn't picking up that transitive dependency and failing to build. If you manually add the `Animations` reference to the UWP app head, then it starts working again... Assuming this is some issue with the old-style project, as the WASDK head works fine (before and after this change).
We'll either have to follow-up with the tooling team and/or find a workaround for this in our props files...
> Remove double-slashes from Project Paths

- components/SettingsControls/samples/ClickableSettingsCardSample.xaml
- components/SettingsControls/samples/SettingsCardSample.xaml
- components/SettingsControls/samples/SettingsControls.Samples.csproj
- components/SettingsControls/samples/SettingsExpanderItemsSourceSample.xaml
- components/SettingsControls/samples/SettingsExpanderSample.xaml
- components/SettingsControls/samples/SettingsPageExample.xaml
- components/SettingsControls/src/SettingsCard/SettingsCard.Properties.cs
- Updated the default `ActionIconToolTip` to `null`, addressing: #171. (`string.Empty` still made the tooltip show with no text)
- Minor sample tweaks to make the XAML a bit less verbose (using our own icon extensions for the icons :))
Tested on WASDK and WASM, not on UWP due to: #169
> [SettingsControls] Updating default tooltip value

- .config/dotnet-tools.json
- .editorconfig
- .github/workflows/build.yml
- Directory.Build.props
- components/Animations/src/ConnectedAnimations/Connected.cs
- components/Animations/src/Enums/FrameworkLayer.cs
- components/Animations/src/Enums/VisualProperty.cs
- components/Animations/src/Expressions/ReferenceNodes/AmbientLightReferenceNode.cs
- components/Animations/src/Xaml/Abstract/CustomAnimation{TValue,TKeyFrame}.cs
- components/Animations/src/Xaml/AnimationSet.cs
- components/Behaviors/src/Notification/StackedNotificationsBehavior.cs
- components/Collections/samples/AdvancedCollectionViewSample.xaml.cs
- components/Collections/samples/IncrementalLoadingCollectionSample.xaml.cs
- components/Converters/src/FileSizeToFriendlyStringConverter.cs
- components/Extensions/src/Element/FrameworkElementExtensions.ActualSize.cs
- components/Extensions/src/Element/FrameworkElementExtensions.Mouse.cs
- components/Extensions/src/Element/UIElementExtensions.cs
- components/Extensions/src/Markup/SymbolIconExtension.cs
- components/Extensions/src/Markup/SymbolIconSourceExtension.cs
- components/Extensions/src/Shadows/AttachedShadowBase.cs
- components/Extensions/src/Shadows/IAttachedShadow.cs
- components/Helpers/samples/CameraHelperSample.xaml.cs
- components/Primitives/src/WrapPanel/StretchChild.cs
- components/Sizers/src/SizerBase.cs
- global.json
Companion PR to https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/117, which should be closed before merging this.
As noted:
> Any codebase consuming the tooling repo will need to be adjusted to account for the new nullable annotations and analyzers added between netstandard2.0 and net7.0.
This PR pulls in the .NET 7 upgrade and fixes the new warnings and errors that appeared in our codebase as a result.
> Upgrade to .NET 7, enable WASM optimizations

- .github/workflows/SignClientFileList.txt
- .github/workflows/build.yml
Updates our build behavior to the following:
- PRs will only be pushed unsigned to the **PullRequest** feeds
- `main` merges will get signed and pushed to the **MainLatest** feeds
- `rel/<major>.<minor>.<date>[-<prereleasetag>]` builds will get signed and pushed to the **MainLatest** feed, then _wait for approval_ before being pushed to _NuGet.org_
- For PR/main - the Version date is grabbed from the last commit in the git log, we needed a stable version date as otherwise the UWP and WASDK build times could cause the versions to be different by a day at the UTC rollover time.
- For Release builds, the Version date is grabbed from the rel/ branch naming (along with any prerelease tag)
- Packages uploaded as artifacts to the feed for main and release builds
- Uses new .NET Foundation …
> Add Package Signing and Release Staging/Pipeline for NuGet.org

- components/Collections/src/AdvancedCollectionView/AdvancedCollectionView.cs
- components/Collections/tests/Test_AdvancedCollectionView.cs
Fixes https://github.com/CommunityToolkit/Windows/issues/78
Carryover from https://github.com/CommunityToolkit/Windows/pull/80
> AdvancedCollectionView: Use generic arguments if possible to get type of elements in list

- components/Primitives/src/WrapLayout/UvBounds.cs
- components/Primitives/src/WrapLayout/UvMeasure.cs
- components/Primitives/src/WrapLayout/WrapItem.cs
- components/Primitives/src/WrapLayout/WrapLayout.cs
- components/Primitives/src/WrapLayout/WrapLayoutState.cs
* Fix: When all the items in WrapLayout are Collapsed, the method WrapLayoutState.GetHeight() would throw "Nullable object must have a value."
* Fix: Once an item is collapsed in the WrapLayout(such as a Image that is loaded later), it would not be visible without refreshing.
* Other: Some code efficiency optimizations.
Fix: #70
The feature in WrapLayout has been implemented by [RiverFlowLayout](https://learn.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.flowlayout?view=winui-2.8). But it is only available in the prerelease versions of WinUI for now.
```xaml
<RiverFlowLayout
ItemsJustification="Start"
ItemsStretch="None"
LineSize="200"
LineSpacing="5"
MinItemSpacing="5" />
```
#73
> Fix: WrapLayout

- Directory.Build.props
Test PR for changes from https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/110
This may require other changes to props files here, but wanted to get it started so we wouldn't forget.
> Update tooling submodule for rebrand changes

- .config/dotnet-tools.json
- .github/workflows/build.yml
See #201 for more details about why we're doing this and related issues.
We can use branch from 201 in the future to move forward when we're ready, later after release.
> Snap to Uno-check 1.13 manifest to resolve build issue

- components/Animations/samples/Animations.Samples.csproj
- components/Behaviors/samples/Behaviors.Samples.csproj
- components/CameraPreview/samples/CameraPreview.Samples.csproj
- components/Collections/samples/Collections.Samples.csproj
- components/DeveloperTools/samples/DeveloperTools.Samples.csproj
- components/Extensions/samples/Extensions.Samples.csproj
- components/HeaderedControls/samples/HeaderedControls.Samples.csproj
- components/Helpers/samples/Helpers.Samples.csproj
- components/ImageCropper/samples/ImageCropper.Samples.csproj
- components/LayoutTransformControl/samples/LayoutTransformControl.Samples.csproj
- components/Media/samples/Media.Samples.csproj
- components/MetadataControl/samples/MetadataControl.Samples.csproj
- components/Primitives/samples/Primitives.Samples.csproj
- components/RadialGauge/samples/RadialGauge.Samples.csproj
- components/RangeSelector/samples/RangeSelector.Samples.csproj
- components/RichSuggestBox/samples/RichSuggestBox.Samples.csproj
- components/Segmented/samples/Segmented.Samples.csproj
- components/SettingsControls/samples/SettingsControls.Samples.csproj
- components/Sizers/samples/SizerBase.Samples.csproj
- components/TokenizingTextBox/samples/TokenizingTextBox.Samples.csproj
- components/Triggers/samples/Triggers.Samples.csproj
Needs https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/129
This PR consists of a tooling update that fixes an asset issue in the sample app.
Component icons and other `.png` files are now included as library assets instead of using the `/SourceAssets` workaround needed for this (now closed) issue: https://github.com/unoplatform/uno/issues/2502.
> Include component icons as library assets

- components/Animations/samples/Animations.Samples.csproj
- components/Animations/samples/ConnectedAnimations.md
- components/Animations/samples/ConnectedAnimationsSample.xaml
- components/Extensions/samples/IconMarkupExtensions.md
- components/Segmented/samples/Segmented.Samples.csproj
- components/Segmented/samples/Segmented.md
- components/Segmented/samples/SegmentedBasicSample.xaml
- components/Segmented/samples/SegmentedStylesSample.xaml
Some minor improvements to:
- Make XAML less verbose (e.g. using our IconExtensions)
- Minor improvements here and there
> Minor sample tweaks

- components/SettingsControls/src/SettingsExpander/SettingsExpander.xaml
As pointed out by @krschau in https://github.com/CommunityToolkit/Labs-Windows/issues/216#issuecomment-1707310372
Setting the `CornerRadius` to of a `SettingsCard` and `SettingsExpander` to 100.
Before:
After:
> [SettingsExpander] Fix for CornerRadius

- .github/workflows/build.yml
- Directory.Build.props
Fixes #220
With this change our `Uwp` based packages won't include the `net6/7-windows` targets/WASDK
And our `WinUI` packages won't include the `uap` target for UWP.
This should enable WAPProjects to better handle this scenario (we'll have to test), and mean that Uno folks can't improperly mix-and-match, they'll need to install the package that corresponds to their Uno.UI/Uno.WinUI setup.
> Update Build so that Uwp package doesn't include WASDK and vice-versa

- components/Collections/samples/AdvancedCollectionView.md
- components/Collections/samples/AdvancedCollectionViewSample.xaml
- components/Collections/samples/AdvancedCollectionViewSample.xaml.cs
- components/Collections/samples/IncrementalLoadingCollection.md
- components/Collections/samples/IncrementalLoadingCollectionSample.xaml
- components/Collections/samples/IncrementalLoadingCollectionSample.xaml.cs
- components/Collections/src/AdvancedCollectionView/AdvancedCollectionView.Defer.cs
- components/Collections/src/AdvancedCollectionView/AdvancedCollectionView.Events.cs
- components/Collections/src/AdvancedCollectionView/AdvancedCollectionView.cs
- components/Collections/src/AdvancedCollectionView/IAdvancedCollectionView.cs
- components/Collections/src/AdvancedCollectionView/SortDescription.cs
- components/Collections/src/AdvancedCollectionView/SortDirection.cs
- components/Collections/src/AdvancedCollectionView/VectorChangedEventArgs.cs
- components/Collections/src/IncrementalLoadingCollection/IIncrementalSource.cs
- components/Collections/src/IncrementalLoadingCollection/IncrementalLoadingCollection.cs
- components/Collections/tests/DataSource.cs
- components/Collections/tests/Test_AdvancedCollectionView.cs
- components/Collections/tests/Test_IncrementalLoadingCollection.cs
`AdvancedCollectionView` and `IncrementalLoadingCollection` now use the `CommunityToolkit.WinUI.Collections` namespace instead of `CommunityToolkit.WinUI`
> Updating Collections namespace

- .github/workflows/build.yml
This should hopefully be all we need for our release build
> Ignore -postfix parameter to PackEachExperiment if prerelease tag is not specified

- .github/workflows/ISSUE_TEMPLATE/bug.yml
- .github/workflows/ISSUE_TEMPLATE/config.yml
- .github/workflows/PULL_REQUEST_TEMPLATE.md
This PR
- Adds the missing Bug Report template, adjusted for this repo
- Adds links for various external resources users may need.
> Added issue templates and links

- components/SettingsControls/samples/ClickableSettingsCardSample.xaml
- components/SettingsControls/samples/SettingsCardSample.xaml
- components/SettingsControls/samples/SettingsExpanderItemsSourceSample.xaml
- components/SettingsControls/src/SettingsCard/SettingsCard.cs
- components/SettingsControls/src/SettingsCard/SettingsCard.xaml
Addressing: https://github.com/CommunityToolkit/Windows/issues/219
Before, when resizing a card where the `Content` is not set or `Content` is set but no `Header` + `Description` the spacing would be applied, resulting in https://github.com/CommunityToolkit/Windows/issues/219.
Before:
After:
To test:
- Add the following XAML to a sample and resize the window:
``` xml
<controls:SettingsCard >
<ComboBox SelectedIndex="0">
<ComboBoxItem>Option 1</ComboBoxItem>
<ComboBoxItem>Option 2</ComboBoxItem>
<ComboBoxItem>Option 3</ComboBoxItem>
</ComboBox>
</controls:SettingsCard>
```
> [SettingsControls] Bugfix for wrapping states

- components/Media/src/Brushes/BackdropGammaTransferBrush.cs
- components/Media/src/Brushes/CanvasBrushBase.cs
- components/Media/src/Brushes/ImageBlendBrush.cs
- components/Media/src/Helpers/SurfaceLoader.Instance.cs
- components/Media/src/Helpers/SurfaceLoader.cs
- components/Media/src/Pipelines/PipelineBuilder.Initialization.cs
- components/Media/src/Pipelines/PipelineBuilder.cs
This PR closes #235, #233
Introduces a hotfix for a regression in the WinUI 3 package where usage of the compositor in the PipelineBuilder resulted in a `NullReferenceException`, caused by usage of `Window.Current.Compositor` instead of the WinUI 3 equivalent.
Still unable to launch the Wasdk sample app head for both the single-component Media solution and the gallery due to #212 and #169. These changes were tested by producing NuGet packages and testing in a blank Wasdk app. 
> Fixed compositor nullreference in WinUI 3

- components/SettingsControls/src/SettingsCard/SettingsCard.cs
- components/SettingsControls/tests/Test_SettingsCard.cs
There was a crash when binding an empty string to Header or Description while the content of SettingsCard was set. This pull request fixes that issue.
Bugfix
When the content of SettingsCard is set, binding an empty string to Header or Description causes a crash.
When the content of SettingsCard is set, binding an empty string to Header or Description will no longer result in a crash.
I would like to explain the fixes in this pull request using XAML simplified for the SettingsCard:
- When initializing the component with the Content property (here, Header) of the ContentPresenter for the Header set to null, a crash occurs due to the ContentPresenter for the Content.
- If the Visibility of the ContentPresenter for the Header is …
> Fixing crash when setting empty string for SettingsCard's Header and Description

- .config/dotnet-tools.json
- .github/workflows/build.yml
This PR upgrades the Uno-Check tool to the latest version 1.18.1
> Update uno-check to 1.18.1

- Directory.Build.props
- components/Animations/samples/Animations.Samples.csproj
- components/Animations/src/CommunityToolkit.WinUI.Animations.csproj
- components/Behaviors/src/CommunityToolkit.WinUI.Behaviors.csproj
- components/CameraPreview/src/CommunityToolkit.WinUI.Controls.CameraPreview.csproj
- components/Collections/src/CommunityToolkit.WinUI.Collections.csproj
- components/Helpers/src/CommunityToolkit.WinUI.Helpers.csproj
- components/ImageCropper/src/CommunityToolkit.WinUI.Controls.ImageCropper.csproj
- components/LayoutTransformControl/src/CommunityToolkit.WinUI.Controls.LayoutTransformControl.csproj
- components/Media/samples/Dependencies.props
- components/Media/samples/Media.Samples.csproj
- components/Media/src/CommunityToolkit.WinUI.Media.csproj
- components/Primitives/samples/Primitives.Samples.csproj
- components/Primitives/src/CommunityToolkit.WinUI.Controls.Primitives.csproj
- components/RadialGauge/src/CommunityToolkit.WinUI.Controls.RadialGauge.csproj
- components/RangeSelector/src/CommunityToolkit.WinUI.Controls.RangeSelector.csproj
- components/RichSuggestBox/src/CommunityToolkit.WinUI.Controls.RichSuggestBox.csproj
- components/Segmented/samples/Segmented.Samples.csproj
- components/Segmented/src/CommunityToolkit.WinUI.Controls.Segmented.csproj
- components/SettingsControls/samples/SettingsControls.Samples.csproj
- components/SettingsControls/src/CommunityToolkit.WinUI.Controls.SettingsControls.csproj
- components/Sizers/src/CommunityToolkit.WinUI.Controls.Sizers.csproj
- components/TokenizingTextBox/src/CommunityToolkit.WinUI.Controls.TokenizingTextBox.csproj
- components/Triggers/src/CommunityToolkit.WinUI.Triggers.csproj
This PR:
- Fixes #212
- Fixes all usages of relative ProjectReference paths to be relative to repo root
- Fixes malformed references to `ToolkitBehaviorsSourceProject` and `ToolkitExtensionsSourceProject`
- Fixed any source path prop names defined in Directory.Build.props that didn't match the component name
Prerequisite PR: https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/163
> Cleanup project references

- components/Animations/src/Implicit.cs
Progress towards #319
Needed for #241
See also https://github.com/CommunityToolkit/Windows/pull/241#issuecomment-1899107130
This PR disables calls to the Composition APIs in the Implicit animation attached property when running under Uno.
> Disable Implicit animations when running under Uno

- components/SettingsControls/samples/SettingsExpanderSample.xaml
- components/SettingsControls/src/Helpers/CornerRadiusConverter.cs
- components/SettingsControls/src/SettingsExpander/SettingsExpander.xaml
Before (corner is blurred/lighter gray caused by the root grid overlapping with the border)
After (corner is sharp)
Fixes: https://github.com/CommunityToolkit/Windows/issues/325
> [SettingsExpander] Fix CornerRadius bug

- components/Primitives/samples/DockPanelSample.xaml
- components/Primitives/src/DockPanel/DockPanel.Properties.cs
- components/Primitives/src/DockPanel/DockPanel.cs
#293  
Enhance: Add spacing properties for `DockPanel`
`HorizontalSpacing` and `VerticalSpacing`
No `HorizontalSpacing` and `VerticalSpacing` property
Has `HorizontalSpacing` and `VerticalSpacing` property
```xml
HorizontalSpacing="5" VerticalSpacing="5"
```
> Enhance: Add spacing properties for `DockPanel`

- components/Animations/src/CommunityToolkit.WinUI.Animations.csproj
- components/Behaviors/src/CommunityToolkit.WinUI.Behaviors.csproj
- components/CameraPreview/src/CommunityToolkit.WinUI.Controls.CameraPreview.csproj
- components/ColorPicker/src/CommunityToolkit.WinUI.Controls.ColorPicker.csproj
- components/Converters/src/CommunityToolkit.WinUI.Converters.csproj
- components/DeveloperTools/src/CommunityToolkit.WinUI.DeveloperTools.csproj
- components/Extensions/src/CommunityToolkit.WinUI.Extensions.csproj
- components/HeaderedControls/src/CommunityToolkit.WinUI.Controls.HeaderedControls.csproj
- components/Helpers/src/CommunityToolkit.WinUI.Helpers.csproj
- components/ImageCropper/src/CommunityToolkit.WinUI.Controls.ImageCropper.csproj
- components/LayoutTransformControl/samples/LayoutTransformControl.md
- components/LayoutTransformControl/src/CommunityToolkit.WinUI.Controls.LayoutTransformControl.csproj
- components/Media/src/CommunityToolkit.WinUI.Media.csproj
- components/MetadataControl/src/CommunityToolkit.WinUI.Controls.MetadataControl.csproj
- components/Primitives/src/CommunityToolkit.WinUI.Controls.Primitives.csproj
- components/RadialGauge/src/CommunityToolkit.WinUI.Controls.RadialGauge.csproj
- components/RangeSelector/src/CommunityToolkit.WinUI.Controls.RangeSelector.csproj
- components/RichSuggestBox/src/CommunityToolkit.WinUI.Controls.RichSuggestBox.csproj
- components/Segmented/src/CommunityToolkit.WinUI.Controls.Segmented.csproj
- components/SettingsControls/src/CommunityToolkit.WinUI.Controls.SettingsControls.csproj
- components/Sizers/src/CommunityToolkit.WinUI.Controls.Sizers.csproj
- components/TabbedCommandBar/src/CommunityToolkit.WinUI.Controls.TabbedCommandBar.csproj
- components/TokenizingTextBox/src/CommunityToolkit.WinUI.Controls.TokenizingTextBox.csproj
- components/Triggers/src/CommunityToolkit.WinUI.Triggers.csproj
In preparation for 8.1, this PR replaces all default Nupkg descriptions. New descriptions were either:
- Pulled from other documentation (e.g. yaml front matter)
- In the case of components with many parts and docs, description is created by listing the features for the component, with the most used features listed first for discovery.
> Added missing package descriptions

- components/Segmented/src/EqualPanel.cs
- Bugfix
LayoutCycleException will be thrown at specific screen scaling ( #359 )
The Segmented can be correctly layout.
- [ x ] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)
- [ x ] Based off latest main branch of toolkit
- [ x ] Tested code with current supported SDKs
- [ x ] Contains **NO** breaking changes
> Segmented - Update EqualPanel to avoid Layout Cycle

- components/Primitives/samples/StaggeredLayoutSample.xaml
- components/Primitives/samples/StaggeredLayoutSample.xaml.cs
- components/Primitives/samples/StaggeredPanelSample.xaml
- components/Primitives/samples/StaggeredPanelSample.xaml.cs
- components/Primitives/src/StaggeredLayout/StaggeredLayout.cs
- components/Primitives/src/StaggeredLayout/StaggeredLayoutItemsStretch.cs
Adaptive Column Width for `StaggeredLayout`
- Refactoring (no functional changes, no api changes)
> Refactor: Adaptive Column Width for StaggeredLayout

- components/Helpers/src/CameraHelper/CameraHelper.cs
- components/Helpers/src/CameraHelper/FrameEventArgs.cs
fix: On the Windows app SDK using CameraHelper, FrameArrived time execution for a period of time will not be triggered.
Maybe my modification is not perfect, but it seems that this can solve the problem of event triggering. I hope you can give some good opinions and suggestions so that this function can be used normally in Windows App SDK applications.
Fixes #375 
Currently, when a video frame arrives, the event is not triggered.
Through my PR I test the video frame in the test code, and the video frame processing event is still triggered for a long time.
https://github.com/CommunityToolkit/Windows/assets/24240675/e983a994-51f5-493e-8ecf-721c8d4df38b
App11 is the test project I use. …
> fix:On the Windows app SDK using CameraHelper, FrameArrived time execution for a period of time will not be triggered.

- components/Converters/samples/Converters.md
- components/Extensions/samples/DispatcherQueueExtensions.md
- components/Extensions/samples/FrameworkElementExtensions.md
- components/Extensions/samples/ShadowAnimations.md
- components/Sizers/samples/GridSplitter.md
This PR commits the changes that fixed the doc warnings reported by https://github.com/MicrosoftDocs/CommunityToolkit/pull/393#issuecomment-2086275811.
> Fixed remaining Microsoft Learn doc warnings

- components/RangeSelector/src/RangeSelector.xaml
- Bugfix
There is a square around Thumbs
No square around thumbs, This workaround is for https://github.com/unoplatform/uno/issues/6457
> fix: Uno Platform - Avoid square border around `RangeSelector` `Thumbs`

- .github/workflows/build.yml
This PR fixes an issue with the CI build on `main` when the "Upload Package List" step is run. See [this](https://github.com/CommunityToolkit/Windows/actions/runs/8903042347/job/24450102902) run for an example of the error.
> Fixed duplicated artifacts in CI when uploading package list

- .github/workflows/build.yml
- components/Collections/samples/IncrementalLoadingCollectionSample.xaml.cs
- components/Collections/src/AdvancedCollectionView/AdvancedCollectionView.cs
- components/Collections/src/IncrementalLoadingCollection/IncrementalLoadingCollection.cs
- components/Converters/src/TaskResultConverter.cs
- components/Extensions/src/Markup/EnumValuesExtension.cs
Enables Native AoT functionality when running under .NET 8 in preparation for the WinAppSdk 1.6 release with NativeAoT support.  
 
Prerequisite PR: https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/190
> Enable AoT for net8 in Release

- components/Animations/src/Extensions/CompositorExtensions.cs
- components/Extensions/src/Element/FrameworkElementExtensions.Mouse.cs
- components/Helpers/src/ThemeListener.cs
This PR:
- Updates our Uno packages to the latest stable version
- Updates the TFMs that Uno runs on from net7.0 to net8.0
- Fixes any issues that arise from the move to net8.0
Prerequisite PR https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/191
> Update Uno version, Uno TFMs to .NET 8

- components/Triggers/src/IsNullOrEmptyStateTrigger.cs
Fixes https://github.com/unoplatform/uno/issues/17311
`FrameworkElement`s in Uno are incorrectly `IEnumerable`s, so they could be considered as empty incorrectly.
> Fix `IsNullOrEmptyStateTrigger` for Uno to consider FEs as non-empty

- components/Sizers/src/SizerBase.Properties.cs
- components/Sizers/src/SizerBase.cs
- Bugfix
Cursor is not set for Sizers on Uno Platform
Cursor is set
> fix: `ProtectedCursor` is now supported in Uno Platform

- .github/workflows/build.yml
- GenerateAllSolution.bat
This PR
- Updates tooling with the latest fixes and improvements to multitarget support for solution generation
- Refactors the `build` job, splitting into `build` and `package`.
- The `build` job is matrixed in line with the multitarget system
- The `package` job is not matrixed and has been refactored to use our `./tooling/Build-Toolkit-Components.ps1` script.
Prerequisite PR: https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/200
> MultiTarget Matrix for CI, support for solution generation 

- ReadMe.md
Updates the build requirements section of the repo README, bumping .NET 6 to 8 and adding the minimum Windows 10 Version the toolkit can be built on.
Tested against:
- Windows 10 Version 1809 Build 17763
- With net8, no Windows SDK (doesn't build)
- With net8, Windows SDK 17763 (doesn't build uwp)
- With net8, Windows SDK 17763 and 19041 (doesn't build uwp)
- Windows 10 Version 21H1 Build 19043
- With net8, no Windows SDK (doesn't build)
- With net8, Windows SDK 17763 (doesn't build uwp)
- With net8, Windows SDK 17763 and 19041 (**builds uwp and wasdk**)
> Update build requirements in readme

- components/Media/src/Brushes/AcrylicBrush.cs
This PR adds `AcrylicBrush` on WinUI 3 again. On this target, the `BackgroundSource` property has been removed.
This type is missing for WinUI 3.
The type is usable again.
> Enable 'AcrylicBrush' in WinUI 3 again

- components/RangeSelector/src/RangeSelector.Input.Drag.cs
Allows adding custom content to the tooltip.
The problem with replacing the tooltipText is that the tooltip completely stops working. I want the container to still work and get placed. The code was doing an unnecessary null check on an object that wasn't being used.
- Bugfix 
Override the style in a subclass that replaces tooltipText with something else makes tooltip stop working.
Presence of the ToolTipText textblock is no longer required.
> Update _toolTip even if toolTipText isn't available

- .github/workflows/build.yml
Needed for https://github.com/CommunityToolkit/Windows/pull/500
> Run CI when merging to dev/* branches

- .github/workflows/build.yml
This PR fixes an issue with our CI where the built UWP and WinUI packages included "All" multitargets. 
Including both doesn't cause issues in UWP or WinUI projects normally as the correct TFM is picked up. However, in certain scenarios uap may be picked up when the winappsdk TFMs were intended, such as in the packaging project for applications using the Windows Application Packaging setup. 
Closes https://github.com/CommunityToolkit/Windows/issues/490#issuecomment-2332805012
> Exclude uap in WinUI package, wasdk in UWP package

- .github/workflows/build.yml
This PR merges the released 8.1.240916 patch containing these changes:
- https://github.com/CommunityToolkit/Windows/pull/500
> Merge patch 8.1.240916 into main

- components/Collections/samples/IncrementalLoadingCollectionSample.xaml
This PR fixes #514
Bugfix
Switches to `{x:Bind}` instead of `{Binding}` and adds an `x:DataType` to the data template. The bound Name property now shows in this sample with AoT enabled.
Guide and templates](https://github.com/CommunityToolkit/WindowsCommunityToolkit-design-assets)
> Fixed AoT data binding in IncrementalLoadingCollectionSample

- components/Behaviors/src/CommunityToolkit.WinUI.Behaviors.csproj
- components/Collections/src/CommunityToolkit.WinUI.Collections.csproj
- components/ColorPicker/src/CommunityToolkit.WinUI.Controls.ColorPicker.csproj
- components/Helpers/src/CommunityToolkit.WinUI.Helpers.csproj
- components/ImageCropper/src/Dependencies.props
- components/Media/src/CommunityToolkit.WinUI.Media.csproj
- components/Media/src/Dependencies.props
- components/Primitives/src/CommunityToolkit.WinUI.Controls.Primitives.csproj
- components/RichSuggestBox/src/CommunityToolkit.WinUI.Controls.RichSuggestBox.csproj
- components/SettingsControls/src/CommunityToolkit.WinUI.Controls.SettingsControls.csproj
- components/TokenizingTextBox/src/CommunityToolkit.WinUI.Controls.TokenizingTextBox.csproj
This PR updates our Win2d dependency to 1.3.0. Notably, this version has a minimum TFM of `net6.0-windows10.0.19041`, wheras the previous 1.1.1 version we were using has a minimum TFM of `net6.0-windows10.0.22621`. 
Since this dependency was the only reason we originally bumped our Windows App SDK TFM to 22621 (see https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/161, https://github.com/microsoft/Win2D/issues/943), we can follow-up with a submodule PR to reduce our TFM back down to 19041.
> Update Microsoft.Graphics.Win2D package reference to version 1.3.0

- components/Collections/samples/AdvancedCollectionView.md
- components/Collections/samples/AdvancedCollectionViewSample.xaml
- components/Collections/samples/AdvancedCollectionViewSample.xaml.cs
- components/Collections/samples/Collections.Samples.csproj
- components/Collections/samples/IncrementalLoadingCollectionSample.xaml
- components/Collections/samples/IncrementalLoadingCollectionSample.xaml.cs
- components/Triggers/src/CompareStateTrigger.cs
- components/Triggers/src/IsEqualStateTrigger.cs
Similar fix to #514 along with a bit of extra clean-up to simplify samples.
Mainly using x:Bind instead of Binding to make sample work with AoT.
Doesn't display information in list.
Information displayed.
Tested in Debug/Release
> Fixes #513 - AdvancedCollectionView not working with AoT

- components/SettingsControls/src/SettingsExpander/SettingsExpander.Properties.cs
Code style update (formatting) 
The summary in SettingsCard was pointing to the wrong types.
Use the correct type based on the Property Name.
> chore: update typos in class properties summary

- global.json
This PR:
- Updates our tooling pointer to the latest `main` commit.
- Updates `global.json` to use version 8.0.403 instead of 8.0.201. This aligns with the version used by our tooling submodule, and enables implicit properties and project references when building with the Windows App SDK (see https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/221#issuecomment-2438628204)
Changes in tooling include:
[New] 
- Components can now override the TFMs using for a declared MultiTarget. See  https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/218
- Components using the `wasdk` MultiTarget can now set `HasWinUI` to `false` to disable any UI-related dependencies under the TFMs used to target the Windows App SDK, aligning with the current behavior on UWP. See …
> Update tooling pointer, bump global.json to 8.0.403

- components/Primitives/samples/Primitives.Samples.csproj
- components/Primitives/samples/SwitchPresenter.md
- components/Primitives/samples/SwitchPresenter/SwitchConverterBrushSample.xaml
- components/Primitives/samples/SwitchPresenter/SwitchConverterBrushSample.xaml.cs
- components/Primitives/samples/SwitchPresenter/SwitchPresenterLayoutSample.xaml.cs
- components/Primitives/samples/SwitchPresenter/SwitchPresenterTemplateSample.xaml
- components/Primitives/samples/SwitchPresenter/SwitchPresenterTemplateSample.xaml.cs
- components/Primitives/samples/SwitchPresenter/SwitchPresenterValueSample.xaml
- components/Primitives/samples/SwitchPresenter/SwitchPresenterValueSample.xaml.cs
- components/Primitives/src/SwitchPresenter/Case.cs
- components/Primitives/src/SwitchPresenter/SwitchConverter.cs
- components/Primitives/src/SwitchPresenter/SwitchHelpers.cs
- components/Primitives/src/SwitchPresenter/SwitchPresenter.cs
- components/Primitives/tests/Primitives.Tests.projitems
- components/Primitives/tests/SwitchPresenter/SwitchConverterBrushSample.xaml
- components/Primitives/tests/SwitchPresenter/SwitchConverterBrushSample.xaml.cs
- components/Primitives/tests/SwitchPresenter/SwitchPresenterLayoutSample.xaml
- components/Primitives/tests/SwitchPresenter/SwitchPresenterLayoutSample.xaml.cs
- components/Primitives/tests/SwitchPresenter/SwitchPresenterTests.cs
Note this _does not_ make an attempt at #516 for WinUI 3, that issue still needs resolution orthogonal to these changes. The specific new functionality works fine and has been tested on UWP, WinUI 3, and Uno Platform WASM.
- New Feature
`ContentPresenter.Content` is an `object` and can take general values/objects beyond just UIElements as it can use a `ContentTemplate` to transform that into UIElements.
This ability has been missing in `SwitchPresenter` as `Case.Content` was restricted to `UIElement` only.
We also have been able to use the same switch like power for transforming values within bindings/expressions.
- `Case.Content` is now an `object`
- This allows us to use `SwitchPresenter.ContentTemplate` and transform data in new ways within …
> SwitchPresenter 2.0 and the new SwitchConverter 🦙❤️

- .github/workflows/build.yml
- Directory.Build.props
This PR attempts to fix the ongoing CI errors caused by GitHub Actions updating the image to include net9.0 unexpectedly. 
This setup forces only the specified dotnet version to be available when `dotnet --list-sdks` is run, avoiding the errors caused by the introduction of dotnet 9 and unblocking us while we work to resolve them in https://github.com/CommunityToolkit/Windows/pull/563.
> Specify directory for dotnet to install to and execute from.

- components/Extensions/samples/Dispatcher/KeyboardDebounceSample.xaml
- components/Extensions/samples/Dispatcher/KeyboardDebounceSample.xaml.cs
- components/Extensions/samples/Dispatcher/MouseDebounceSample.xaml
- components/Extensions/samples/Dispatcher/MouseDebounceSample.xaml.cs
- components/Extensions/samples/DispatcherQueueTimerExtensions.md
- components/Extensions/src/Dispatcher/DispatcherQueueTimerExtensions.cs
- components/Extensions/tests/DispatcherQueueTimerExtensionTests.cs
This PR does a lot of clean-up for the Debounce function, it adds:
- More tests for a variety of scenarios for using Debounce
- Adds Samples for Keyboard and Mouse debouncing using these APIs and improvements
- Fixes the issue when switching the same timer from trailing to leading mode where the requested action would not fire immediately.
- Switch to using ConditionalWeakTable instead of ConcurrentDictionary to ensure we don't capture the DispatcherQueueTimer
- Fixes #143 the issue of immediate not working well by setting `IsRepeating` on the timer to false during initialization. FYI @huynhsontung - This shouldn't effect your own registrations to the `Tick` method, if you're using Debounce, there should only be the one timer per Debounce, and your `Tick` should be called whenever the …
> Improvements to DispatcherQueueTimer.Debounce extension

- components/Extensions/samples/ListViewExtensions.md
- components/Extensions/samples/ListViewExtensionsAlternateColorSample.xaml
- components/Extensions/samples/ListViewExtensionsAlternateColorSample.xaml.cs
- components/Extensions/src/ListViewBase/ListViewExtensions.AlternateRows.cs
This PR copies the content from [here](https://github.com/CommunityToolkit/WindowsCommunityToolkit/pull/4865) over to 8.x, as the [original issue](https://github.com/CommunityToolkit/Windows/issues/327) is still valid.
Fixes #327. 
- Bugfix
The alternate row colors are only visible on hover.
The alternate row colors are visible immediately.
> Fix issue with Windows 11 ListViewStyle

- components/Primitives/src/StaggeredLayout/StaggeredLayout.cs
closes #542 
fix <https://github.com/microsoft/PowerToys/pull/35139>
> Fix: StaggeredLayout division bug

- components/Primitives/src/StaggeredLayout/StaggeredLayout.cs
- components/Primitives/src/StaggeredLayout/StaggeredLayoutState.cs
> Fix: prevent StaggeredLayout floating point errors

- GenerateAllSolution.bat
This PR fixes solution generation issues when end users open the default `GenerateAllSolution.bat` by only enabling the default minimum MultiTargets (uwp, wasdk, wasm).  
The underlying issue affects solution generation when `android`, `ios` or `macos` MultiTargets are requested or enabled. These targets don't have corresponding gallery or test heads that can be built, so they're unnecessary and have been disabled. This does not affect our ability to build these targets in CI.
Issue also reported in the [Windows App Community Discord](https://discord.com/channels/372137812037730304/669640275500466197/1314138588232945695).
> Fix solution generation via default .bat

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/build.yml
- Directory.Build.targets
- components/Behaviors/src/Dependencies.props
- components/Converters/src/ResourceNameToResourceStringConverter.cs
- components/Extensions/src/Text/StringExtensions.Localization.cs
- components/Media/src/Dependencies.props
- global.json
This PR updates our tooling to .NET 9.0.100, including updates to:
- TargetFrameworks
- Added alongside existing TFMs for Uno and Wasdk
- Update tooling to handle multi-tfm value for Uno
- Dockerfile and devcontainer (used by VS Code, locally & Codespaces)
- GitHub Actions CI (build.yml)
- global.json (selects dotnet version used by runtime)
- Dependent packages (Uno Platform)
- Misc error fixes in components for net9.0.
Prerequisite PR:
https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/230
> Upgrade to .NET 9.0

- components/ColorPicker/src/ColorPicker.xaml
- components/ColorPicker/src/Converters/NullToTransparentConverter.cs
`GridView.SelectedValue` to null is transient behavior. It does not affect the original `ColorPicker` behavior.
closes: #414
- Bugfix
> Fix: ColorPicker Binding failed

- components/ImageCropper/src/Dependencies.props
- components/Media/src/Dependencies.props
This PR just includes two changes:
- Bumps Win2D to latest
- Removes a polyfill package on UWP .NET 8
> Bump Win2D dependencies

- components/Media/samples/AttachedCardShadow.md
> Fixed a small typo

- .config/dotnet-tools.json
- .github/workflows/build.yml
- Directory.Build.props
- components/Behaviors/src/Headers/FadeHeaderBehavior.cs
- components/Behaviors/src/Headers/HeaderBehaviorBase.cs
- components/ImageCropper/src/ImageCropperThumb.cs
- components/Media/src/Helpers/SurfaceLoader.Instance.cs
- components/Primitives/src/SwitchPresenter/SwitchConverter.cs
- components/Primitives/src/SwitchPresenter/SwitchHelpers.cs
- components/Segmented/src/EqualPanel.cs
- components/Segmented/src/Helpers/SegmentedMarginConverter.cs
- components/Segmented/src/Segmented/Segmented.cs
- components/Segmented/src/SegmentedItem/SegmentedItem.cs
- components/SettingsControls/src/Helpers/StyleExtensions.cs
- components/SettingsControls/src/SettingsCard/SettingsCard.Properties.cs
- components/SettingsControls/src/SettingsCard/SettingsCard.cs
- components/SettingsControls/src/SettingsCard/SettingsCardAutomationPeer.cs
- components/SettingsControls/src/SettingsExpander/SettingsExpander.ItemsControl.cs
- components/SettingsControls/src/SettingsExpander/SettingsExpander.Properties.cs
- components/SettingsControls/src/SettingsExpander/SettingsExpander.cs
- components/SettingsControls/src/SettingsExpander/SettingsExpanderAutomationPeer.cs
- components/TokenizingTextBox/src/TokenizingTextBox.cs
- components/Triggers/src/IsNullOrEmptyStateTrigger.cs
This PR
- Fixes several errors related to missing XMLDoc comments.
- Updates our uno.check version to the latest 1.27.4
- Attempts unblock our CI
Prerequisite PR https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/249
> Fix sudden CI errors

- components/Behaviors/src/Dependencies.props
Updates the XamlBehaviors package.
- Build or CI related changes
> Update XamlBehaviors to 3.0.0

- .config/dotnet-tools.json
This PR fixes build errors that spontaneously occurred when generating the solution, likely due to a tooling update. Updating slngen to the lates version fixes the issue.
> Fixes solution generation issues by updating slngen

- components/SettingsControls/src/SettingsExpander/SettingsExpander.Properties.cs
> Fix invalid XML comment in SettingsExpander

- components/TokenizingTextBox/src/TokenizingTextBox.xaml
- components/TokenizingTextBox/src/TokenizingTextBoxItem.AutoSuggestBox.xaml
The AutoSuggestBoxStyle dependency property is not hooked up to the AutoSuggestBox's style in TokenizingTextBoxItemTextStyle. Is uses the static resource SystemAutoSuggestBoxStyle.
This fix sets the AutoSuggestBox's style in TokenizingTextBoxItemTextStyle to the AutoSuggestBoxStyle of the TokenizingTextBox and sets the AutoSuggestBoxStyle's default value to that of SystemAutoSuggestBoxStyle.
Bugfix
TokenizingTextBox's AutoSuggestBoxStyle is not applied
TokenizingTextBox's AutoSuggestBoxStyle is applied
- [X ] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)
- [X ] Based off latest main branch of toolkit
- [ X] Tested code with current supported SDKs
- [ X] Contains **NO** breaking changes
> Hook up TokenizingTextBox AutoSuggestBoxStyle 

- components/Behaviors/src/Dependencies.props
This PR bumps our dependency on `Uno.Microsoft.Xaml.Behaviors.Interactivity` and `Uno.Microsoft.Xaml.Behaviors.Interactivity.WinUI` to a stable version, removing our dependency on the prerelease version of 3.x originally added alongside UWP .NET 9 support. 
Prerequisite PR https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/287
> Update Uno Behaviors to 3.0.3

- .github/workflows/build.yml
This PR fixes the error observed at [this CI run](https://github.com/CommunityToolkit/Labs-Windows/actions/runs/17837578593/job/50718577918) by installing the .NET 6 SDK explicitly.
Log for failed CI step:
```
Run powershell -version 5.1 -command "./ApplyXamlStyling.ps1 -Passive" -ErrorAction Stop
Use 'Help .\ApplyXamlStyling.ps1' for more info or '-Main' to run against all files.
Restoring dotnet tools...
Tool 'uno.check' (version '1.27.4') was restored. Available commands: uno-check
Tool 'xamlstyler.console' (version '3.2206.4') was restored. Available commands: xstyler
Tool 'microsoft.visualstudio.slngen.tool' (version '12.0.13') was restored. Available commands: slngen
Restore was successful.
Checking all files (passively)
You must install or update .NET to run this application.
App: …
```
> Install .NET 6 SDK to re-enable XAML Styler
